name: Publish helm chart

on:
  push:
    branches: [ main ]
    paths:
      - 'Chart.yaml'

env:
  HELM_S3_PLUGIN_VERSION: "v0.10.0"
  S3_BUCKET_CHARTS_DIR: charts
  S3_BUCKET_NAME: svmt-helm-repo-s3

jobs:
  push_to_helm_repo:
    name: Publish helm chart to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prep helm chart
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Get chart version for Chart.yaml
          CHART_VERSION=$(grep -E '^version:' Chart.yaml | awk '{print $2}')
          # Install helm S3 plugin
          helm plugin install https://github.com/hypnoglow/helm-s3.git --version ${{ env.HELM_S3_PLUGIN_VERSION }}
          # Add helm repo
          helm repo add demo "s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_BUCKET_CHARTS_DIR }}"
          # Create helm package
          helm package .
          # Push package to the repo
          helm s3 push --relative ./aws-bucket-reader-${CHART_VERSION}.tgz demo
          # Update repository index
          helm s3 reindex demo
